# Generated by Django 6.0.7 on 2026-07-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorzis', '0002_tailor_chest_tailor_height_tailor_hip_tailor_inseam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, null=True),
        ),
    ]
