# Generated by Django 6.0.7 on 2026-07-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorzis', '0003_alter_tailor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='height',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='inseam',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='shoulder',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='sleeve',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='weight',
        ),
    ]
